name: MazeApp

options:
  xcodeVersion: '9999'

targets:
  MazeAppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      SWIFT_VERSION: 5
      IPHONEOS_DEPLOYMENT_TARGET: 15.4
    info:
      path: "./MazeApp/Info.plist"
      properties:
        CFBundleDisplayName: "MazeApp"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1.0.0"
        CFBundleIdentifier: "com.mazeapp.joao"

    sources:
      - path: MazeAppTests

    dependencies:
      - target: MazeApp

  MazeApp:
    type: application
    platform: iOS
    settings:
      SWIFT_VERSION: 5
      IPHONEOS_DEPLOYMENT_TARGET: 15.4
    sources: [MazeApp]
